name: Verify Build Consistency

on:
  pull_request:

jobs:
  check-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          check-latest: true
          cache: npm

      - name: Create .env file from secret
        run: echo "$DOT_ENV" > .env
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}

      - name: Install dependencies
        run: npm ci

      - name: Run build script
        run: npm run build

      - name: Check for changes in dist/Soluna.mjs
        run: |
          git add dist/Soluna.mjs
          if ! git diff --cached --quiet; then
            echo 'Error: dist/Soluna.mjs has uncommitted changes after build' >&2
            git diff --cached
            exit 1
          fi
